---
- hosts: all
  tasks:
  - name: Install DNS Role
    win_feature: >
         name=DNS
         include_management_tools=yes
         include_sub_features=yes
         state=present
    register: result
