---
- hosts: all
  tasks:
  - name: Disable Remote Desktop
    ansible.windows.win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
      value: fDenyTSConnections
      data: 0
      datatype: dword
  - name: Firewall rule to allow RDP on TCP port 3389
    win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      profiles: private
      state: present
      enabled: yes
